language: swift
os: osx
osx_image: xcode9.2
before_script:
- gem install xcpretty
script:
- swift package generate-xcodeproj
- set -o pipefail && xcodebuild -scheme travis-ci-Package clean build | xcpretty